const Images = {
    not_nilc: require('./images/lineUp/not_nilc.jpg'),
    smile: require('./images/partners/smile-logo.svg'),
    ntdil: require('./images/partners/ntdil.jpeg'),
    abacha_kitchen: require('./images/vendors/abacha-kitchen.jpeg'),
    bj_asun: require('./images/vendors/bj_asun.jpeg'),
    crispy_grill: require('./images/vendors/crispy-grill.jpeg'),
    doubleB: require('./images/vendors/doubleB.jpeg'),
    dShawarma: require('./images/vendors/dShawarma.jpeg'),
    oliver_signatures: require('./images/vendors/oliver-signatures.jpeg'),
    palms_bamboo: require('./images/vendors/palms-bamboo.jpeg'),
    party_palmwine: require('./images/vendors/party-palmwine.jpeg'),
    popcorn_palace: require('./images/vendors/popcorn-palace.jpeg'),
    boutDrinks: require('./images/vendors/boutDrinks.jpeg'),
    wilsons: require('./images/vendors/wilsons.png'),
    media1: require('./images/media/media1.jpeg'),
    media2: require('./images/media/media2.jpeg'),
    media3: require('./images/media/media3.jpeg'),
    media4: require('./images/media/media4.jpeg'),
    media5: require('./images/media/media5.jpeg'),
    media6: require('./images/media/media6.jpeg'),
    arrow: require('./images/arrow.png'),
    instagramW: require('./images/instagram-w.png'),
    instagramC: require('./images/instagram-c.png'),
    fbC: require('./images/facebook-c.png'),
    fbW: require('./images/facebook-w.png'),
    twitterW: require('./images/twitter-w.png'),
    twitterC: require('./images/twitter-c.png'),
    menu: require('./images/menu.png'),
}

export default Images;